# DO NOT CHANGE the "init" and "install" sections below
#######################################################

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap


# Adapt as necessary starting from here
services:
  - mssql2012sp1

build_script:
  - ps: iex .\inst\CIDatabase\CIBuild_DBCreate.ps1
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

environment:
  global:
    R_CHECK_ARGS: "--no-manual --as-cran --run-donttest"
    R_ARCH: x64
    WARNINGS_ARE_ERRORS: 1

  matrix:
    - R_VERSION: release
      R_ARCH: x64
    
    # - R_VERSION: devel
    #   R_ARCH: x64

    - R_VERSION: release
      R_ARCH: i386
    
    # - R_VERSION: devel
    #   R_ARCH: i386

#---------------------------------#
#  notifications configuration    #
#---------------------------------#

notifications:
 - provider: Email
   to:
     - healthcatalystslc+appveyor@mailbox.org
   subject: 'r-appveyor build {{status}}'
   on_build_success: false
   on_build_failure: true
